import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import { formatIndianDateTime } from "./format";

const TEMPLE_NAME = "Temple Finance System";
const TEMPLE_LINE_1 = "Neelkanth Mahadev Mandir";
const TEMPLE_LINE_2 = "Gulab Bari Ajmer";
const TEMPLE_ADDRESS = `${TEMPLE_LINE_1}, ${TEMPLE_LINE_2}`;

function fileDate() {
  return new Date().toISOString().slice(0, 10);
}

function formatAmount(amount) {
  return `Rs. ${Number(amount || 0).toLocaleString("en-IN")}`;
}

function addPdfHeader(doc, title) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text(TEMPLE_NAME, 14, 16);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(TEMPLE_LINE_1, 14, 24);
  doc.text(TEMPLE_LINE_2, 14, 31);
  doc.text("Generated:", 14, 40);
  doc.text(formatIndianDateTime(new Date().toISOString()), 14, 47);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(title, 14, 59);
  doc.setFont("helvetica", "normal");
}

function addTableTitle(doc, title, y) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text(title, 14, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  return y + 5;
}

function addPdfFooter(doc) {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i += 1) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(
      "Generated by Temple Finance System",
      14,
      doc.internal.pageSize.getHeight() - 10
    );
  }
}

function savePdf(doc, name) {
  addPdfFooter(doc);
  doc.save(`${name}-${fileDate()}.pdf`);
}

function saveWorkbook(workbook, name) {
  XLSX.writeFile(workbook, `${name}-${fileDate()}.xlsx`);
}

function sheetFromRows(rows) {
  return XLSX.utils.aoa_to_sheet(rows);
}

function incomeRows(records) {
  return records.map((row, index) => [
    index + 1,
    formatIndianDateTime(row.created_at),
    row.Name,
    Number(row.Amount || 0),
    row.Mode,
  ]);
}

function expenseRows(records) {
  return records.map((row, index) => [
    index + 1,
    formatIndianDateTime(row.created_at),
    row.Title,
    Number(row.Amount || 0),
    row.Mode,
  ]);
}

export function downloadDashboardPdf({ income, expense, summary }) {
  const doc = new jsPDF();
  addPdfHeader(doc, "Complete Finance Summary");

  autoTable(doc, {
    startY: addTableTitle(doc, "Financial Summary", 70),
    head: [["Summary", "Amount"]],
    body: [
      ["Total Income", formatAmount(summary.totalIncome)],
      ["Total Expense", formatAmount(summary.totalExpense)],
      ["Current Balance", formatAmount(summary.balance)],
    ],
    theme: "grid",
  });

  autoTable(doc, {
    startY: addTableTitle(doc, "Income Records", doc.lastAutoTable.finalY + 12),
    head: [["Date & Time (IST)", "Donor Name", "Amount", "Payment Mode"]],
    body: income.map((row) => [
      formatIndianDateTime(row.created_at),
      row.Name,
      formatAmount(row.Amount),
      row.Mode,
    ]),
    theme: "grid",
  });

  autoTable(doc, {
    startY: addTableTitle(doc, "Expense Records", doc.lastAutoTable.finalY + 12),
    head: [["Date & Time (IST)", "Title", "Amount", "Payment Mode"]],
    body: expense.map((row) => [
      formatIndianDateTime(row.created_at),
      row.Title,
      formatAmount(row.Amount),
      row.Mode,
    ]),
    theme: "grid",
  });

  savePdf(doc, "dashboard-report");
}

export function downloadDashboardExcel({ income, expense, summary }) {
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(
    workbook,
    sheetFromRows([
      [TEMPLE_NAME],
      [TEMPLE_ADDRESS],
      ["Report Generated", formatIndianDateTime(new Date().toISOString())],
      [],
      ["Summary", "Amount"],
      ["Total Income", summary.totalIncome],
      ["Total Expense", summary.totalExpense],
      ["Current Balance", summary.balance],
    ]),
    "Summary"
  );
  XLSX.utils.book_append_sheet(
    workbook,
    sheetFromRows([
      ["S.No", "Date & Time", "Donor Name", "Amount", "Payment Mode"],
      ...incomeRows(income),
    ]),
    "Income"
  );
  XLSX.utils.book_append_sheet(
    workbook,
    sheetFromRows([
      ["S.No", "Date & Time", "Title", "Amount", "Payment Mode"],
      ...expenseRows(expense),
    ]),
    "Expenses"
  );
  saveWorkbook(workbook, "dashboard-report");
}

export function downloadIncomePdf(records) {
  const doc = new jsPDF();
  addPdfHeader(doc, "Income Report");
  autoTable(doc, {
    startY: addTableTitle(doc, "Income Records", 70),
    head: [["S.No", "Date & Time", "Donor Name", "Amount", "Payment Mode"]],
    body: incomeRows(records).map((row) => [
      row[0],
      row[1],
      row[2],
      formatAmount(row[3]),
      row[4],
    ]),
    theme: "grid",
  });
  savePdf(doc, "income-report");
}

export function downloadIncomeExcel(records) {
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(
    workbook,
    sheetFromRows([
      [TEMPLE_NAME],
      [TEMPLE_ADDRESS],
      ["Report Generated", formatIndianDateTime(new Date().toISOString())],
      [],
      ["S.No", "Date & Time", "Donor Name", "Amount", "Payment Mode"],
      ...incomeRows(records),
    ]),
    "Income Records"
  );
  saveWorkbook(workbook, "income-report");
}

export function downloadExpensePdf(records) {
  const doc = new jsPDF();
  addPdfHeader(doc, "Expense Report");
  autoTable(doc, {
    startY: addTableTitle(doc, "Expense Records", 70),
    head: [["S.No", "Date & Time", "Title", "Amount", "Payment Mode"]],
    body: expenseRows(records).map((row) => [
      row[0],
      row[1],
      row[2],
      formatAmount(row[3]),
      row[4],
    ]),
    theme: "grid",
  });
  savePdf(doc, "expense-report");
}

export function downloadExpenseExcel(records) {
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(
    workbook,
    sheetFromRows([
      [TEMPLE_NAME],
      [TEMPLE_ADDRESS],
      ["Report Generated", formatIndianDateTime(new Date().toISOString())],
      [],
      ["S.No", "Date & Time", "Title", "Amount", "Payment Mode"],
      ...expenseRows(records),
    ]),
    "Expense Records"
  );
  saveWorkbook(workbook, "expense-report");
}

export function downloadUpiPdf({ pending, converted }) {
  const doc = new jsPDF();
  addPdfHeader(doc, "UPI To Cash Report");
  autoTable(doc, {
    startY: addTableTitle(doc, "Pending UPI Transactions", 70),
    head: [["Date", "Donor Name", "Amount"]],
    body: pending.map((row) => [
      formatIndianDateTime(row.created_at),
      row.Name,
      formatAmount(row.Amount),
    ]),
    theme: "grid",
  });
  autoTable(doc, {
    startY: addTableTitle(doc, "Conversion History", doc.lastAutoTable.finalY + 12),
    head: [["Conversion Date", "Amount Converted"]],
    body: converted.map((row) => [
      formatIndianDateTime(row.updated_at || row.created_at),
      formatAmount(row.Amount),
    ]),
    theme: "grid",
  });
  savePdf(doc, "upi-report");
}

export function downloadUpiExcel({ pending, converted }) {
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(
    workbook,
    sheetFromRows([
      [TEMPLE_NAME],
      [TEMPLE_ADDRESS],
      ["Report Generated", formatIndianDateTime(new Date().toISOString())],
      [],
      ["Date", "Donor Name", "Amount"],
      ...pending.map((row) => [
        formatIndianDateTime(row.created_at),
        row.Name,
        Number(row.Amount || 0),
      ]),
    ]),
    "Pending UPI"
  );
  XLSX.utils.book_append_sheet(
    workbook,
    sheetFromRows([
      ["Conversion Date", "Amount Converted"],
      ...converted.map((row) => [
        formatIndianDateTime(row.updated_at || row.created_at),
        Number(row.Amount || 0),
      ]),
    ]),
    "Conversions"
  );
  saveWorkbook(workbook, "upi-report");
}
